// react/src/App/index.js
import React from 'react';
import {
  BrowserRouter as Router,
  Switch,
  Route,
  // Link
} from "react-router-dom";
import Firebase from 'firebase'
import firebaseConfig from '../firebase-config'
import './style.css';
import Header from '../header'
import Nav from '../nav'
import LandingPage from '../landingPage'
import Footer from '../footer'
import Blog from "../blog"
import Post from "../post"
import FourOhFour from "../four-oh-four"

Firebase.initializeApp(firebaseConfig);

function App() {
  return (
    <div className="App">
        <Router>
            <Route exact path="/" component={Header}/>
            <Nav/>
            <Route exact path="/" component={LandingPage} />
            <Switch>
              <Route exact path="/blog">
                <Blog firebase={Firebase} />
              </Route>
              <Route exact path="/posts/:id">
                <Post firebase={Firebase} />
              </Route>
              <Route component={FourOhFour} />
            </Switch>
            <Footer/>
        </Router>
    </div>
  );
}

export default App;

// ng-front/src/app/app.component.ts
import { Component } from '@angular/core';
import * as firebase from 'firebase';
import { firebaseConfig } from './firebase-config';
import { Router } from '@angular/router';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  constructor(private router: Router) {
    firebase.initializeApp(firebaseConfig);
  }


}

<div class="container">
  <app-header></app-header>
  <div class="row">
    <div class="col-xs-12">
      <router-outlet></router-outlet>
    </div>
  </div>      
  <app-footer></app-footer>
</div>
